version: '3.8'

services:

  redis:
    image: redis
    container_name: auth_session_exam_redis
    ports:
      - "6379:6379"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: auth_session_exam_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auth_session_exam
      POSTGRES_USER: mydev
      POSTGRES_PASSWORD: mydev
      LANG: en_US.UTF-8

volumes:
  pgdata: